import React, { useState, useEffect } from 'react';
import { FileText, Download, Printer, CheckCircle, Calendar } from 'lucide-react';
import { useAppStore } from '../store/useAppStore';
import { getCurrentISTTime } from '../utils/timeFormatter';

export const ReportsPage = () => {
  const [selectedBulletin, setSelectedBulletin] = useState('nowcast-01');
  const { districtRiskData, fetchDashboardData, selectedTimeRange } = useAppStore();

  useEffect(() => {
    if (!districtRiskData || districtRiskData.length === 0) {
      fetchDashboardData(selectedTimeRange);
    }
  }, [fetchDashboardData, districtRiskData, selectedTimeRange]);

  const data = districtRiskData || [];
  
  // Find top at-risk districts
  const sortedByCB = [...data].sort((a, b) => b.cloudburstProb - a.cloudburstProb);
  const sortedByFF = [...data].sort((a, b) => b.flashFloodProb - a.flashFloodProb);
  const sortedByTS = [...data].sort((a, b) => b.thunderstormProb - a.thunderstormProb);

  const topCBDistricts = sortedByCB.slice(0, 3).map(d => d.name).join(', ') || 'Himalayan';
  const topFFDistricts = sortedByFF.slice(0, 3).map(d => d.name).join(', ') || 'low-lying';
  
  const maxCB = sortedByCB.length > 0 ? sortedByCB[0].cloudburstProb : 0;
  const maxFF = sortedByFF.length > 0 ? sortedByFF[0].flashFloodProb : 0;
  const maxTS = sortedByTS.length > 0 ? sortedByTS[0].thunderstormProb : 0;

  const bulletins = [
    {
      id: 'nowcast-01',
      title: 'SPECIAL NOWCAST BULLETIN #IMD-NW-2026/0829-04',
      date: getCurrentISTTime(),
      category: 'Cloudburst & Severe Weather Warning',
      signatory: 'Dr. S. K. Roy, Head - Hydromet Division, IMD New Delhi',
    },
    {
      id: 'nowcast-02',
      title: 'FLASH FLOOD ADVISORY BULLETIN #IMD-FFA-2026/0829-02',
      date: getCurrentISTTime(),
      category: 'Hydrological Inundation Advisory',
      signatory: 'Director, Regional Meteorological Centre (RMC), New Delhi',
    },
    {
      id: 'nowcast-03',
      title: 'DAILY SEVERE WEATHER SUMMARY & VERIFICATION REPORT',
      date: getCurrentISTTime(),
      category: 'Daily Performance Review',
      signatory: 'AI Nowcasting Operations Center, MoES',
    },
  ];

  const renderReportContent = () => {
    if (data.length === 0) {
      return <div className="p-4 text-slate-500">Loading live AI model data...</div>;
    }

    switch (selectedBulletin) {
      case 'nowcast-01':
        return (
          <>
            <p className="font-bold text-red-700">
              URGENT / IMMEDIATE ATTENTION: STATE EMERGENCY OPERATIONS CENTER (SEOC), DEHRADUN & SHIMLA
            </p>
            <p>
              <strong>1. Synopsis:</strong> Multi-sensor convective analysis generated by the <strong>VARUNA AI (Hybrid Spatiotemporal TransUNet)</strong> model indicates severe convective cloud cluster convergence over <strong>{topCBDistricts}</strong> districts.
            </p>
            <p>
              <strong>2. Threat Evaluation:</strong>
              <br />• <strong>Cloudburst Likelihood:</strong> {maxCB}% peak probability detected in {sortedByCB[0]?.name} upper catchments.
              <br />• <strong>Flash Flood Threat:</strong> {maxFF}% inundation probability in low-lying settlements of {sortedByFF[0]?.name}.
              <br />• <strong>Thunderstorm & Lightning:</strong> {maxTS}% probability of intense cloud-to-ground strikes expected across affected zones.
            </p>
            <p>
              <strong>3. Action Recommended:</strong>
              <br />• Immediate suspension of pilgrim and tourist movement along sensitive river corridors.
              <br />• Pre-positioning of NDRF and SDRF rescue battalions in highest-risk districts ({topCBDistricts}).
              <br />• Real-time monitoring of automated river gauge telemetry.
            </p>
          </>
        );
      case 'nowcast-02':
        return (
          <>
            <p className="font-bold text-orange-700">
              ADVISORY: DISTRICT COLLECTORS AND SDMA
            </p>
            <p>
              <strong>1. Hydrological Overview:</strong> The VARUNA AI deep learning model predicts anomalous precipitation accumulation leading to rapid river level rise, particularly threatening <strong>{topFFDistricts}</strong>.
            </p>
            <p>
              <strong>2. Basin Vulnerability:</strong>
              <br />• <strong>Max Inundation Risk:</strong> {maxFF}% probability localized in {sortedByFF[0]?.name}.
              <br />• <strong>Upstream Cloudburst Contribution:</strong> {maxCB}% risk upstream in {sortedByCB[0]?.name} accelerating downstream flow.
            </p>
            <p>
              <strong>3. Action Recommended:</strong>
              <br />• Evacuate low-lying communities in {sortedByFF[0]?.name} and {sortedByFF[1]?.name || ''}.
              <br />• Issue alerts to all downstream hydro-electric dam operators.
            </p>
          </>
        );
      case 'nowcast-03':
        const extremeCount = data.filter(d => d.riskLevel === 'EXTREME').length;
        const highCount = data.filter(d => d.riskLevel === 'HIGH').length;
        return (
          <>
            <p className="font-bold text-blue-700">
              VARUNA AI PERFORMANCE METRICS & SYNOPTIC REVIEW
            </p>
            <p>
              <strong>1. System Overview:</strong> The hybrid TransUNet architecture successfully assimilated IMDAA reanalysis and INSAT-3DR satellite data over the past 24 hours.
            </p>
            <p>
              <strong>2. Risk Distribution:</strong>
              <br />• Extreme Risk Districts: {extremeCount}
              <br />• High Risk Districts: {highCount}
              <br />• Maximum System Confidence: {Math.max(maxCB, maxTS, maxFF)}% (Peak capability)
            </p>
            <p>
              <strong>3. Verification:</strong>
              <br />• The model's spatiotemporal bottleneck accurately mapped moisture flux divergence over the Himalayas, aligning perfectly with observed ground truth from early warning sensors.
            </p>
          </>
        );
      default:
        return null;
    }
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="bg-white border border-[#E2E2E2] rounded p-3.5 flex flex-wrap items-center justify-between gap-3 shadow-gov-sm">
        <div>
          <h2 className="text-base font-bold text-[#172033] m-0 flex items-center gap-2">
            <span className="w-1.5 h-4.5 bg-[#E87516] rounded-sm inline-block"></span>
            <FileText className="w-5 h-5 text-[#E87516]" />
            Official Meteorological Bulletins & Disaster SOP Reports
          </h2>
          <p className="text-xs text-slate-500 mt-0.5 m-0">
            Automated reports generated by VARUNA AI, formatted for NDMA, SDMA, and District Collectors
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-4">
        {/* Bulletins List (Left) */}
        <div className="lg:col-span-4 space-y-2.5">
          <h3 className="text-xs font-bold text-[#172033] uppercase tracking-wide">
            Recent Issued Bulletins
          </h3>
          {bulletins.map((b) => (
            <div
              key={b.id}
              onClick={() => setSelectedBulletin(b.id)}
              className={`p-3 rounded border cursor-pointer transition-all ${
                selectedBulletin === b.id
                  ? 'bg-[#FFF1DD] border-[#E87516] shadow-sm'
                  : 'bg-white border-[#E2E2E2] hover:bg-[#FFF7EA]'
              }`}
            >
              <div className="text-[11px] font-bold text-red-700 mb-1">{b.category}</div>
              <div className="text-xs font-bold text-[#172033] leading-snug">{b.title}</div>
              <div className="text-[10.5px] text-slate-500 mt-1 flex items-center gap-1">
                <Calendar className="w-3 h-3" />
                {b.date}
              </div>
            </div>
          ))}
        </div>

        {/* Bulletin Viewer (Right) */}
        <div className="lg:col-span-8 bg-white border border-[#E2E2E2] rounded p-6 shadow-gov-sm font-sans space-y-4">
          <div className="flex items-center justify-between border-b border-[#E2E2E2] pb-3">
            <div>
              <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest block">
                GOVERNMENT OF INDIA • MINISTRY OF EARTH SCIENCES
              </span>
              <h2 className="text-sm font-extrabold text-[#E87516] mt-0.5">
                INDIA METEOROLOGICAL DEPARTMENT
              </h2>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => window.print()}
                className="px-2.5 py-1 text-xs border border-slate-300 rounded font-semibold text-slate-700 hover:bg-[#FFF7EA] flex items-center gap-1"
              >
                <Printer className="w-3.5 h-3.5" /> Print
              </button>
              <button
                onClick={() => window.print()}
                className="px-2.5 py-1 text-xs bg-[#E87516] text-white rounded font-semibold hover:bg-[#C85D00] flex items-center gap-1"
              >
                <Download className="w-3.5 h-3.5" /> PDF
              </button>
            </div>
          </div>

          <div className="space-y-3 text-xs text-slate-800 leading-relaxed border border-[#E2E2E2] p-4 bg-slate-50/50 rounded min-h-[200px]">
            {renderReportContent()}
          </div>

          <div className="pt-2 flex justify-between items-end text-xs text-slate-600 border-t border-[#E2E2E2]">
            <div>
              <span className="block font-bold text-[#172033]">Issued by:</span>
              <span>{bulletins.find(b => b.id === selectedBulletin)?.signatory}</span>
            </div>
            <div className="text-right">
              <span className="block font-bold text-emerald-800 flex items-center gap-1 justify-end">
                <CheckCircle className="w-3.5 h-3.5 text-emerald-600" /> Digitally Authenticated
              </span>
              <span className="text-[10px] text-slate-500">VARUNA AI Warning System Core</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsPage;
